[package]
name = "ario-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ario-core = { path = "../ario-core" }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }