[package]
name = "ario-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ario-core = { path = "../ario-core" }
bon = { workspace = true }
derive_more = { version = "2.0", features = ["full"] }
futures-concurrency = "7.6"
futures-lite = { workspace = true }
itertools = "0.14"
maybe-owned = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_with = { workspace = true, features = ["base64"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tokio-util = { workspace = true, features = ["time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
anyhow = "1"